apiVersion: apps/v1
kind: Deployment
metadata:
  name: useyu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: useyu
  template:
    metadata:
      labels:
        app: useyu
    spec:
      containers:
      - image: okteto.dev/useyu:latest
        name: useyu
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "ef760124-f2eb-4d34-9281-2f19bdad5433"
        - name: Vless_Path
          value: "/vldereghgksd"
        - name: Vmess_UUID
          value: "ef760124-f2eb-4d34-9281-2f19bdad5433"
        - name: Vmess_Path
          value: "/vmesdfsey"
        - name: Share_Path
          value: "/v2link"
